/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimpleRouteImport } from './routes/simple'
import { Route as PerfTracksRouteImport } from './routes/perf-tracks'
import { Route as MediumRouteImport } from './routes/medium'
import { Route as FragmentRefsRouteImport } from './routes/fragment-refs'
import { Route as EdgeRouteImport } from './routes/edge'
import { Route as ConcurrentStoresRouteImport } from './routes/concurrent-stores'
import { Route as ComplexRouteImport } from './routes/complex'
import { Route as CompilerIdeRouteImport } from './routes/compiler-ide'
import { Route as AutoEffectsRouteImport } from './routes/auto-effects'
import { Route as IndexRouteImport } from './routes/index'

const SimpleRoute = SimpleRouteImport.update({
  id: '/simple',
  path: '/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfTracksRoute = PerfTracksRouteImport.update({
  id: '/perf-tracks',
  path: '/perf-tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const MediumRoute = MediumRouteImport.update({
  id: '/medium',
  path: '/medium',
  getParentRoute: () => rootRouteImport,
} as any)
const FragmentRefsRoute = FragmentRefsRouteImport.update({
  id: '/fragment-refs',
  path: '/fragment-refs',
  getParentRoute: () => rootRouteImport,
} as any)
const EdgeRoute = EdgeRouteImport.update({
  id: '/edge',
  path: '/edge',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcurrentStoresRoute = ConcurrentStoresRouteImport.update({
  id: '/concurrent-stores',
  path: '/concurrent-stores',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexRoute = ComplexRouteImport.update({
  id: '/complex',
  path: '/complex',
  getParentRoute: () => rootRouteImport,
} as any)
const CompilerIdeRoute = CompilerIdeRouteImport.update({
  id: '/compiler-ide',
  path: '/compiler-ide',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoEffectsRoute = AutoEffectsRouteImport.update({
  id: '/auto-effects',
  path: '/auto-effects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auto-effects': typeof AutoEffectsRoute
  '/compiler-ide': typeof CompilerIdeRoute
  '/complex': typeof ComplexRoute
  '/concurrent-stores': typeof ConcurrentStoresRoute
  '/edge': typeof EdgeRoute
  '/fragment-refs': typeof FragmentRefsRoute
  '/medium': typeof MediumRoute
  '/perf-tracks': typeof PerfTracksRoute
  '/simple': typeof SimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auto-effects': typeof AutoEffectsRoute
  '/compiler-ide': typeof CompilerIdeRoute
  '/complex': typeof ComplexRoute
  '/concurrent-stores': typeof ConcurrentStoresRoute
  '/edge': typeof EdgeRoute
  '/fragment-refs': typeof FragmentRefsRoute
  '/medium': typeof MediumRoute
  '/perf-tracks': typeof PerfTracksRoute
  '/simple': typeof SimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auto-effects': typeof AutoEffectsRoute
  '/compiler-ide': typeof CompilerIdeRoute
  '/complex': typeof ComplexRoute
  '/concurrent-stores': typeof ConcurrentStoresRoute
  '/edge': typeof EdgeRoute
  '/fragment-refs': typeof FragmentRefsRoute
  '/medium': typeof MediumRoute
  '/perf-tracks': typeof PerfTracksRoute
  '/simple': typeof SimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auto-effects'
    | '/compiler-ide'
    | '/complex'
    | '/concurrent-stores'
    | '/edge'
    | '/fragment-refs'
    | '/medium'
    | '/perf-tracks'
    | '/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auto-effects'
    | '/compiler-ide'
    | '/complex'
    | '/concurrent-stores'
    | '/edge'
    | '/fragment-refs'
    | '/medium'
    | '/perf-tracks'
    | '/simple'
  id:
    | '__root__'
    | '/'
    | '/auto-effects'
    | '/compiler-ide'
    | '/complex'
    | '/concurrent-stores'
    | '/edge'
    | '/fragment-refs'
    | '/medium'
    | '/perf-tracks'
    | '/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutoEffectsRoute: typeof AutoEffectsRoute
  CompilerIdeRoute: typeof CompilerIdeRoute
  ComplexRoute: typeof ComplexRoute
  ConcurrentStoresRoute: typeof ConcurrentStoresRoute
  EdgeRoute: typeof EdgeRoute
  FragmentRefsRoute: typeof FragmentRefsRoute
  MediumRoute: typeof MediumRoute
  PerfTracksRoute: typeof PerfTracksRoute
  SimpleRoute: typeof SimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simple': {
      id: '/simple'
      path: '/simple'
      fullPath: '/simple'
      preLoaderRoute: typeof SimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perf-tracks': {
      id: '/perf-tracks'
      path: '/perf-tracks'
      fullPath: '/perf-tracks'
      preLoaderRoute: typeof PerfTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medium': {
      id: '/medium'
      path: '/medium'
      fullPath: '/medium'
      preLoaderRoute: typeof MediumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fragment-refs': {
      id: '/fragment-refs'
      path: '/fragment-refs'
      fullPath: '/fragment-refs'
      preLoaderRoute: typeof FragmentRefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edge': {
      id: '/edge'
      path: '/edge'
      fullPath: '/edge'
      preLoaderRoute: typeof EdgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concurrent-stores': {
      id: '/concurrent-stores'
      path: '/concurrent-stores'
      fullPath: '/concurrent-stores'
      preLoaderRoute: typeof ConcurrentStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complex': {
      id: '/complex'
      path: '/complex'
      fullPath: '/complex'
      preLoaderRoute: typeof ComplexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compiler-ide': {
      id: '/compiler-ide'
      path: '/compiler-ide'
      fullPath: '/compiler-ide'
      preLoaderRoute: typeof CompilerIdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-effects': {
      id: '/auto-effects'
      path: '/auto-effects'
      fullPath: '/auto-effects'
      preLoaderRoute: typeof AutoEffectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutoEffectsRoute: AutoEffectsRoute,
  CompilerIdeRoute: CompilerIdeRoute,
  ComplexRoute: ComplexRoute,
  ConcurrentStoresRoute: ConcurrentStoresRoute,
  EdgeRoute: EdgeRoute,
  FragmentRefsRoute: FragmentRefsRoute,
  MediumRoute: MediumRoute,
  PerfTracksRoute: PerfTracksRoute,
  SimpleRoute: SimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
